//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        public int id { get; set; }
        [Required(ErrorMessage ="This field is required.")]
        public string name { get; set; }
        public string description { get; set; }
        public string category { get; set; }
        public string manufacturer { get; set; }
        public string supplier { get; set; }
        public Nullable<decimal> price { get; set; }
    }
}
